### ISSUE TITLE
cubdb crashes during update

### ISSUE THREAD

**Issue by tduccuong** [lucaong/cubdb#31]
Hi, I am using CubDB as embedded time-series statistics. The CubDB process crashes randomly with errors like this:

```
2021-02-19 08:18:23.055 [error] GenServer #PID<0.2284.0> terminating
** (stop) exited in: GenServer.call(#PID<0.2285.0>, {:update, #Function<0.77404542/1 in CubDB.Store.CubDB.Store.File.close/1>}, 5000)
    ** (EXIT) time out
    (elixir 1.11.2) lib/gen_server.ex:1027: GenServer.call/3
    (cubdb 1.0.0-rc.7) lib/cubdb/store/file.ex:106: CubDB.Store.CubDB.Store.File.close/1
    (stdlib 3.13) gen_server.erl:718: :gen_server.try_terminate/3
    (stdlib 3.13) gen_server.erl:903: :gen_server.terminate/10
    (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message (from Tg.Service.BackgroundSrv): {:put_and_delete_multi, [{{"UserStatM", "user@domain.com", "potential", 1613719092948961}, %{cat_ids: ["chatting", "social_network"], created_at: 1613719092948961, domain: "discord.com", filter_id: nil, n_occurs: 1, path: "", scheme: "", type: "dns", url: "discord.com", user_id: "user@domain.com", user_ip: "149.224.20.202", verdict: "potential"}}], []}
State: %CubDB.State{auto_compact: {100, 0.25}, auto_file_sync: true, btree: %CubDB.Btree{capacity: 32, dirt: 202, root: {:b, [<key1>, <key2>,…]}, root_loc: 1005235, size: 655, store: %CubDB.Store.File{file_path: "/path/to/db_folder/8.cub", pid: #PID<0.2285.0>}}, catch_up: nil, clean_up: #PID<0.2286.0>, clean_up_pending: false, compactor: nil, data_dir: "/path/to/db_folder", readers: %{}, subs: [], task_supervisor: #PID<0.2287.0>}
Client Tg.Service.BackgroundSrv is alive

    (stdlib 3.13) gen.erl:208: :gen.do_call/4
    (elixir 1.11.2) lib/gen_server.ex:1024: GenServer.call/3
    (elixir 1.11.2) lib/enum.ex:792: anonymous fn/3 in Enum.each/2
    (stdlib 3.13) maps.erl:233: :maps.fold_1/3
    (elixir 1.11.2) lib/enum.ex:2197: Enum.each/2
    (firegate_stat 0.1.0) lib/fg/stat/buffer.ex:107: Fg.Stat.Buffer.flush_stat_points/1
    (exservice 0.1.0) lib/tg/service/background_srv.ex:136: Tg.Service.BackgroundSrv.run_job/3
    (exservice 0.1.0) lib/tg/service/background_srv.ex:83: Tg.Service.BackgroundSrv.handle_info/2
2021-02-19 08:18:23.064 [error] GenServer #PID<0.2287.0> terminating
** (stop) exited in: GenServer.call(#PID<0.2285.0>, {:update, #Function<0.77404542/1 in CubDB.Store.CubDB.Store.File.close/1>}, 5000)
    ** (EXIT) time out
Last message: {:EXIT, #PID<0.2284.0>, {:timeout, {GenServer, :call, [#PID<0.2285.0>, {:update, #Function<0.77404542/1 in CubDB.Store.CubDB.Store.File.close/1>}, 5000]}}}
State: %DynamicSupervisor{args: {{:temporary, 5000}, []}, children: %{}, extra_arguments: [], max_children: :infinity, max_restarts: 3, max_seconds: 5, mod: Task.Supervisor, name: {#PID<0.2287.0>, Task.Supervisor}, restarts: [], strategy: :one_for_one}
2021-02-19 08:18:23.065 [error] GenServer Tg.Service.BackgroundSrv terminating
** (stop) exited in: GenServer.call(#PID<0.2284.0>, {:put_and_delete_multi, [{<key>, <value>}], []}, :infinity)
    ** (EXIT) exited in: GenServer.call(#PID<0.2285.0>, {:update, #Function<0.77404542/1 in CubDB.Store.CubDB.Store.File.close/1>}, 5000)
        ** (EXIT) time out
    (elixir 1.11.2) lib/gen_server.ex:1027: GenServer.call/3
    (elixir 1.11.2) lib/enum.ex:792: anonymous fn/3 in Enum.each/2
    (stdlib 3.13) maps.erl:233: :maps.fold_1/3
    (elixir 1.11.2) lib/enum.ex:2197: Enum.each/2
    (firegate_stat 0.1.0) lib/fg/stat/buffer.ex:107: Fg.Stat.Buffer.flush_stat_points/1
    (exservice 0.1.0) lib/tg/service/background_srv.ex:136: Tg.Service.BackgroundSrv.run_job/3
    (exservice 0.1.0) lib/tg/service/background_srv.ex:83: Tg.Service.BackgroundSrv.handle_info/2
    (stdlib 3.13) gen_server.erl:680: :gen_server.try_dispatch/4
Last message: {:run_every, "vMt5TEFnzDX2NIHIVN", 1000, [report_to: Fg.Stat.Buffer, action_id: :flush_result]}
State: %Tg.Service.BackgroundSrv.State{jobs: %{"vMt5TEFnzDX2NIHIVN" => #Function<3.23596830/0 in Fg.Stat.Buffer.handle_info/2>}, pid: Tg.Service.BackgroundSrv}
2021-02-19 08:18:23.069 [info] Tg.Service.BackgroundSrv started.
2021-02-19 08:18:23.067 [error] Ranch protocol #PID<0.2383.0> of listener Fg.Stat.Server (connection #PID<0.2382.0>, stream id 1) terminated
an exception was raised:
    ** (ErlangError) Erlang error: {{:timeout, {GenServer, :call, [#PID<0.2285.0>, {:update, #Function<0.77404542/1 in CubDB.Store.CubDB.Store.File.close/1>}, 5000]}}, {GenServer, :call, [#PID<0.2284.0>, {:read, {:select, [min_key: {"UserStatM", "user@domain.com", "intercept", 1613114299016432}, max_key: {"UserStatM", "user@domain.com", "intercept", 1613719099016483}, pipe: [filter: #Function<12.108285932/1 in Fg.Stat.Api.get_user_stats/2>, map: #Function<13.108285932/1 in Fg.Stat.Api.get_user_stats/2>], reduce: {%{}, #Function<7.108285932/2 in Fg.Stat.Api.handle_req/5>}]}, :infinity}, :infinity]}}
        (elixir 1.11.2) lib/gen_server.ex:1027: GenServer.call/3
        (firegate_stat 0.1.0) lib/fg/stat/api.ex:154: anonymous fn/5 in Fg.Stat.Api.get_user_stats/2
        (firegate_stat 0.1.0) lib/fg/stat/server.ex:2: Fg.Stat.Server.init/2
        (cowboy 2.8.0) /home/ct/Projects/TruongGroup/firegate/firegate_stat/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.8.0) /home/ct/Projects/TruongGroup/firegate/firegate_stat/deps/cowboy/src/cowboy_stream_h.erl:300: :cowboy_stream_h.execute/3
        (cowboy 2.8.0) /home/ct/Projects/TruongGroup/firegate/firegate_stat/deps/cowboy/src/cowboy_stream_h.erl:291: :cowboy_stream_h.request_process/3
        (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
2021-02-19 08:18:23.094 [error] Ranch protocol #PID<0.2387.0> of listener Fg.Stat.Server (connection #PID<0.2382.0>, stream id 2) terminated
an exception was raised:
    ** (ErlangError) Erlang error: {:noproc, {GenServer, :call, [#PID<0.2284.0>, {:read, {:select, [min_key: {"UserStatM", "user@domain.com", "intercept", 1613114303076681}, max_key: {"UserStatM", "user@domain.com", "intercept", 1613719103076729}, pipe: [filter: #Function<12.108285932/1 in Fg.Stat.Api.get_user_stats/2>, map: #Function<13.108285932/1 in Fg.Stat.Api.get_user_stats/2>], reduce: {%{}, #Function<6.108285932/2 in Fg.Stat.Api.handle_req/5>}]}, :infinity}, :infinity]}}
```

Here is how I started CubDB

```
{:ok, pid}  = CubDB.start_link([
      data_dir:   "/path/to/db_folder",
      auto_compact: true
    ])
```

Btw, I am not sure how to refer to a CubDB process started in a supervision tree, because the API for calling CubDB is 
```
CubDb.put_multi(<PID>, <data>)
```

instead of 
```
CubDB.put_multi(:some_atom_id, <data>)
```

I am sorry that some details in the error messages have been concealed due to confidentiality.

Thank you very much for your advice!

**Comment by lucaong** [comment]
@tduccuong hi and sorry for the delayed response!

Regarding your second question, if you start `CubDB` as a named process, you can refer to it with an atom:

```elixir
{:ok, pid}  = CubDB.start_link([
  data_dir:   "/path/to/db_folder",
  auto_compact: true,
  name: :some_atom_id
])

# You can now refer to CubDB by name:
CubDB.put_multi(:some_atom_id, <data>)
```

Regarding the crash, are you using the latest `1.0.0-rc.7` version? The release candidates introduced many fixes and improvements, so if you aren't using the latest version already, try upgrading (the data file is still perfectly backward compatible).

**Comment by tduccuong** [comment]
Thanks a lot! 
I am not writing lots of data, so maybe was slowing the disk down. I am using Linode, not sure if they were doing something during that time, coz since then I have not seen this crash again...

Anyway, I will try out `rc.7` and monitor the system and get back to you if there is still problem.

Cheers for your good product!

**Comment by lucaong** [comment]
Thanks @tduccuong !
I will close the issue for now, as I am confident that you won't see more timeouts with `rc.7`, but feel free to comment on the issue, and I will reopen it if there is more to it.

Cheers!

**Comment by tduccuong** [comment]
Hi @lucaong !

I got the crash again today, even with `rc.7`:
```
2021-03-06 11:38:59.238 [error] GenServer #PID<0.2285.0> terminating
** (stop) exited in: GenServer.call(#PID<0.10647.0>, {:get, #Function<6.77404542/1 in CubDB.Store.CubDB.Store.File.sync/1>}, 5000)
    ** (EXIT) time out
    (elixir 1.11.2) lib/gen_server.ex:1027: GenServer.call/3
    (cubdb 1.0.0-rc.7) lib/cubdb/btree.ex:227: CubDB.Btree.sync/1
    (cubdb 1.0.0-rc.7) lib/cubdb.ex:1033: CubDB.do_put_and_delete_multi/3
    (cubdb 1.0.0-rc.7) lib/cubdb.ex:920: CubDB.handle_call/3
    (stdlib 3.13) gen_server.erl:706: :gen_server.try_handle_call/4
    (stdlib 3.13) gen_server.erl:735: :gen_server.handle_msg/6
    (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message (from BackgroundSrv): {:put_and_delete_multi, [{{"UserStatM", “test_user@gmail.com", "intercept", 1615027131573931}, <data>}}], []}
State: %CubDB.State{auto_compact: {100, 0.25}, auto_file_sync: true, btree: %CubDB.Btree{capacity: 32, dirt: 1433, root: {:b, [<data>]}, root_loc: 9519123, size: 7609, store: %C
ubDB.Store.File{file_path: “/path/to/db/14.cub”, pid: #PID<0.10647.0>}}, catch_up: nil, clean_up: #PID<0.2287.0>, clean_up_pending: false,
compactor: nil, data_dir: “/path/to/db”, readers: %{}, subs: [], task_supervisor: #PID<0.2288.0>}
```

There is no special disk activity around this time and there is no data peak coming to the server as well...

Could you please advice?

Thanks a lot!

**Comment by lucaong** [comment]
Hi @tduccuong ,
Thanks for reporting this. Let me have a look, you might be onto something.

**Comment by lucaong** [comment]
hi @tduccuong ,
it turns out that this last timeout you posted was a different instance of a similar issue. Version `v1.0.0-rc.8`, which was just published on Hex, fixes all the remaining GenServer timeouts and should solve your issue too. Thanks for reporting this!

On a separate note, these timeouts can only occur when the disk is occasionally very slow: in the last one you posted, it took more than 5 seconds to flush the OS disk buffer and sync to the filesystem. If you are not writing massively, this is unusual (and in fact the issue did not surface before. You should not see more timeout errors from CubDB, but you might still want to check if your Linode has some disk issue.

**Comment by tduccuong** [comment]
Hi @lucaong, 

thanks a lot for the quick response! I am building the rc.8 now. I will also closely monitor the linode disk activities.

Cheers for the good product, I really enjoy using CubDB so far :+1:

**Comment by lucaong** [comment]
Thanks for the nice words :)
