### ISSUE TITLE
Running out of disk space

### ISSUE THREAD

**Issue by dominicletz** [lucaong/cubdb#60]
Probably not too relevant but I've received this `arithmetic` error when running out of disk space:

```
10:44:30.212 [error] Process #PID<0.253.0> raised an exception
** (ArithmeticError) bad argument in arithmetic expression
    (cubdb 2.0.0) lib/cubdb/store/file.ex:110: CubDB.Store.CubDB.Store.File.get_node/2
    (cubdb 2.0.0) lib/cubdb/btree.ex:398: CubDB.Btree.lookup_leaf/4
    (cubdb 2.0.0) lib/cubdb/btree.ex:293: CubDB.Btree.insert_terminal_node/4
    (cubdb 2.0.0) lib/cubdb/transaction.ex:228: CubDB.Tx.put/3 
    (cubdb 2.0.0) lib/cubdb.ex:754: anonymous fn/3 in CubDB.put/3
    (cubdb 2.0.0) lib/cubdb.ex:671: CubDB.transaction/2
    (dets_plus 2.1.1) bench/bench.ex:125: anonymous fn/5 in DetsPlus.Bench.large_write_test/2
    (elixir 1.13.4) lib/enum.ex:4136: Enum.reduce_range/5
    (dets_plus 2.1.1) bench/bench.ex:124: DetsPlus.Bench.large_write_test/2
    (stdlib 3.15) timer.erl:181: :timer.tc/2
    (dets_plus 2.1.1) bench/bench.ex:194: DetsPlus.Bench.tc/2
    (dets_plus 2.1.1) bench/bench.ex:174: anonymous fn/6 in DetsPlus.Bench.run/3
    (elixir 1.13.4) lib/enum.ex:4136: Enum.reduce_range/5
    (dets_plus 2.1.1) bench/bench.ex:168: anonymous fn/7 in DetsPlus.Bench.run/3
    (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (dets_plus 2.1.1) bench/bench.ex:165: DetsPlus.Bench.run/3
    (elixir 1.13.4) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
```

**Comment by lucaong** [comment]
@dominicletz good point, it should ideally be a more informative error.

**Comment by lucaong** [comment]
This was turned into a more informative error in `v2.0.1`, just released on Hex. Thanks again for reporting!
